version: 1.13.0.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  lsltag: 1.13.0-b13
  lslversion: 1.13.0
  LSLDIST_URL: "https://github.com/sccn/liblsl/releases/download"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
install:
- cmd: appveyor DownloadFile %LSLDIST_URL%/%lsltag%/liblsl-%lslversion%-Win64.7z -FileName liblsl_x64.7z
- cmd: 7z x liblsl_x64.7z -oLSL
build_script:
- cmd: cmake -S . -B build -DLSL_INSTALL_ROOT=LSL/
- cd build
- cmake --build . --config Release --target install
- cpack -C Release
artifacts:
- path: 'build/*.7z'
